# -*- coding: utf-8 -*-
"""
test_single_orchestrator_flow.py — Golden Multi-Agent Contract & Deliberation Integration Tests
==============================================================================================
Validates the data contracts, schema compliance, and deliberation handoffs defined in:
  • Directive 12.1 (Sole Orchestrator Mandate)
  • PURE_ANTIGRAVITY_DELIBERATION_PROTOCOL.md
  • .agents/shared/schemas/ (stats_results, thesis_audit, claim_evidence, psychometric_summary)

Ensures that checkpoint artifacts generated by 'The Hands' and reviewed by 'The Brains & Critics'
strictly adhere to structural, statistical, and typographical invariants without failures.
"""

import os
import sys
import json
import unittest
from datetime import datetime

REPO_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
SHARED_DIR = os.path.join(REPO_ROOT, ".agents", "shared")
SCHEMAS_DIR = os.path.join(SHARED_DIR, "schemas")
MEMORY_DIR = os.path.join(REPO_ROOT, ".agents", "memory")
REASONING_DIR = os.path.join(REPO_ROOT, ".agents", "reasoning")
VERIF_DIR = os.path.join(REPO_ROOT, ".agents", "verification")
SCRIPTS_DIR = os.path.join(REPO_ROOT, "scripts")
COPILOT_DIR = os.path.join(REPO_ROOT, ".agents", "skills", "digital-twin-academic-consultant", "scripts")

for p in [SHARED_DIR, MEMORY_DIR, REASONING_DIR, VERIF_DIR, SCRIPTS_DIR, COPILOT_DIR]:
    if p not in sys.path and os.path.isdir(p):
        sys.path.insert(0, p)

from case_memory_engine import CaseMemoryEngine
from decision_journal_engine import DecisionJournalEngine
from multi_signal_anomaly_detector import MultiSignalAnomalyDetector
from defense_committee_simulator import DefenseCommitteeSimulator
from statistical_reasoner import StatisticalReasoner
from copilot_bridge import TelegramCopilotBridge
from serve_webapp import test_server as run_web_test_server


def validate_json_contract(payload: dict, schema: dict) -> tuple[bool, list]:
    """Pure-Python structural validator verifying required fields, types, and properties."""
    errors = []
    
    # Verify required top-level properties
    for req in schema.get("required", []):
        if req not in payload:
            errors.append(f"Missing required property: '{req}'")
            
    # Verify property types
    properties = schema.get("properties", {})
    for key, val in payload.items():
        if key in properties:
            expected_type = properties[key].get("type")
            if expected_type == "string" and not isinstance(val, str):
                errors.append(f"Property '{key}' expected string, got {type(val).__name__}")
            elif expected_type == "integer" and not isinstance(val, int):
                errors.append(f"Property '{key}' expected integer, got {type(val).__name__}")
            elif expected_type == "number" and not isinstance(val, (int, float)):
                errors.append(f"Property '{key}' expected number, got {type(val).__name__}")
            elif expected_type == "array" and not isinstance(val, list):
                errors.append(f"Property '{key}' expected array, got {type(val).__name__}")
            elif expected_type == "object" and not isinstance(val, dict):
                errors.append(f"Property '{key}' expected object, got {type(val).__name__}")

    return len(errors) == 0, errors


class TestSingleOrchestratorDeliberationFlow(unittest.TestCase):
    """End-to-End Golden Verification of Pure Antigravity Deliberation Protocol."""

    def setUp(self):
        self.cbr = CaseMemoryEngine()
        self.detector = MultiSignalAnomalyDetector()
        self.defense_sim = DefenseCommitteeSimulator()
        self.stat_reasoner = StatisticalReasoner()

    def test_schema_files_exist_and_parse(self):
        """Asserts all 5 contract schemas in .agents/shared/schemas/ are valid JSON Schema."""
        schema_names = [
            "stats_results.schema.json",
            "claim_evidence.schema.json",
            "psychometric_summary.schema.json",
            "orchestrator_manifest.schema.json",
            "thesis_audit.schema.json"
        ]
        for name in schema_names:
            path = os.path.join(SCHEMAS_DIR, name)
            self.assertTrue(os.path.exists(path), f"Schema not found: {path}")
            with open(path, "r", encoding="utf-8") as f:
                schema = json.load(f)
            self.assertEqual(schema.get("$schema"), "http://json-schema.org/draft-07/schema#")
            self.assertIn("title", schema)
            self.assertIn("required", schema)

    def test_stats_results_checkpoint_contract(self):
        """Simulates Stage 4 statistical-expert calculation output and verifies schema compliance."""
        schema_path = os.path.join(SCHEMAS_DIR, "stats_results.schema.json")
        with open(schema_path, "r", encoding="utf-8") as f:
            schema = json.load(f)

        mock_stage4_output = {
            "project_title": "Effectiveness of ACT on Occupational Burnout",
            "sample_size": 60,
            "analysis_timestamp": datetime.now().isoformat(),
            "descriptive_statistics": [
                {"variable": "Burnout_Post", "group": "Intervention", "n": 30, "mean": 24.35, "sd": 4.12, "skewness": 0.12, "kurtosis": -0.25},
                {"variable": "Burnout_Post", "group": "Control", "n": 30, "mean": 38.60, "sd": 4.85, "skewness": -0.08, "kurtosis": 0.15}
            ],
            "assumptions": {
                "normality_p": 0.342,
                "levene_p": 0.418,
                "box_m_p": 0.520,
                "multicollinearity_vif_max": 1.42
            },
            "hypotheses_results": [
                {
                    "hypothesis_id": "H1",
                    "formulation": "ACT significantly reduces burnout in nurses compared to control.",
                    "test_type": "ancova",
                    "test_statistic": "F",
                    "value": 28.45,
                    "df": [1, 57],
                    "p_value": 0.001,
                    "effect_size_type": "partial_eta_squared",
                    "effect_size_value": 0.33,
                    "verdict": "confirmed"
                }
            ]
        }

        valid, errors = validate_json_contract(mock_stage4_output, schema)
        self.assertTrue(valid, f"stats_results failed schema validation: {errors}")

    def test_thesis_audit_checkpoint_contract(self):
        """Simulates Stage 5 statistical-auditor output and verifies schema compliance."""
        schema_path = os.path.join(SCHEMAS_DIR, "thesis_audit.schema.json")
        with open(schema_path, "r", encoding="utf-8") as f:
            schema = json.load(f)

        mock_stage5_audit = {
            "thesis_title": "Effectiveness of ACT on Occupational Burnout",
            "audit_timestamp": datetime.now().isoformat(),
            "tis_score": 96.5,
            "readiness_verdict": "CLEAR_FOR_DEFENSE",
            "discrepancy_counts": {"critical": 0, "major": 0, "minor": 1},
            "dimensions": {
                "hypothesis_alignment": [{"hypothesis_id": "H1", "aligned": True}],
                "methodology_statistics": [{"test_id": "T1", "df_check": "PASS", "msai_status": "LOW_RISK"}],
                "citation_reconciliation": {"orphaned_citations": 0, "ghost_references": 0},
                "apa7_typography": [{"rule": "leading_zeros", "status": "COMPLIANT"}],
                "adversarial_defense": {
                    "contribution_originality": "High",
                    "effect_size_plausibility": "Plausible",
                    "method_reproducibility": "Complete",
                    "assumption_completeness": "Verified",
                    "claim_evidence_soundness": "Strong",
                    "hostile_referee_questions": [
                        {
                            "dimension": "Statistical Control",
                            "probe_question": "Why was ANCOVA chosen over repeated measures?",
                            "suggested_defense_response": "ANCOVA possesses superior power and controls for baseline regression.",
                            "risk_level": "LOW"
                        }
                    ]
                }
            }
        }

        valid, errors = validate_json_contract(mock_stage5_audit, schema)
        self.assertTrue(valid, f"thesis_audit failed schema validation: {errors}")

    def test_critic_generator_barrier_rejection(self):
        """Protocol 1: Asserts statistical-auditor flags fabricated/anomalous data."""
        anomalous_payload = {
            "tests": [
                {"test_id": "T1", "method": "ancova", "partial_eta_squared": 0.65}  # Unusually extreme effect size
            ],
            "descriptives": {
                "groups": [
                    {"name": "Exp", "mean": 45.0, "sd": 0.8},   # Severe variance deflation
                    {"name": "Ctrl", "mean": 18.0, "sd": 1.1}
                ],
                "skewness": [0.000, 0.000]                      # Unnatural zero skewness
            },
            "reliability": {"DV": 0.995}                        # Suspiciously high alpha
        }

        res = self.detector.evaluate_payload(anomalous_payload)
        self.assertTrue(res["verdict"].startswith("FLAG_FOR_REVIEW"), "Auditor must flag anomalous statistics!")
        self.assertGreaterEqual(res["active_signals_count"], 2)
        self.assertGreaterEqual(res["anomaly_index"], 40.0)

    def test_critic_generator_barrier_clearance(self):
        """Protocol 1: Asserts statistical-auditor approves realistic, authentic empirical statistics."""
        authentic_payload = {
            "tests": [
                {"test_id": "T1", "method": "ancova", "partial_eta_squared": 0.24}
            ],
            "descriptives": {
                "groups": [
                    {"name": "Exp", "mean": 28.35, "sd": 4.15},
                    {"name": "Ctrl", "mean": 36.80, "sd": 4.60}
                ],
                "skewness": [0.18, -0.22]
            },
            "reliability": {"DV": 0.84}
        }

        res = self.detector.evaluate_payload(authentic_payload)
        self.assertEqual(res["verdict"], "NORMAL_EMPIRICAL")
        self.assertEqual(res["active_signals_count"], 0)
        self.assertLess(res["anomaly_index"], 30.0)

    def test_protocol_2_viva_voce_defense_simulation(self):
        """Protocol 2: Asserts final-judge generates 5-role viva voce examination challenges."""
        study_profile = {
            "title": "Effectiveness of ACT on Nurse Burnout",
            "design": "ancova",
            "sample_size": 60,
            "iv": "ACT Therapy",
            "dv": "Occupational Burnout"
        }

        res = self.defense_sim.generate_defense_cross_examination(study_profile)
        self.assertIn("challenges", res)
        self.assertEqual(len(res["challenges"]), 5, "Must generate exactly 5 examiner challenges")
        
        summary = res["defense_readiness_summary"]
        self.assertIn("defense_readiness_percentage", summary)
        self.assertGreaterEqual(summary["defense_readiness_percentage"], 80)
        self.assertIn("rubric_weights", summary)
        self.assertEqual(len(summary["rubric_weights"]), 5)

    def test_case_memory_cbr_retrieval(self):
        """Directive 1: Asserts CaseMemoryEngine reliably retrieves real precedents without hallucination."""
        cases = self.cbr.cases
        self.assertEqual(len(cases), 23, f"Expected 23 historical cases in memory, found {len(cases)}")

        # Search for burnout precedent
        results = self.cbr.search_precedents("burnout", top_k=1)
        self.assertGreater(len(results), 0)
        top_match = results[0]["case"]
        self.assertEqual(top_match["case_id"], "case_001_act_burnout")
        self.assertIn("ANCOVA", top_match["statistical_analysis"])

    def test_statistical_reasoning_10_step_decision_tree(self):
        """Layer 3: Asserts StatisticalReasoner strictly applies 10-step decision tree."""
        # Scenario: 2 groups, pre-post, normal -> ANCOVA
        profile = {
            "topic": "Mindfulness Intervention",
            "objective": "difference",
            "design": "pre_post_control",
            "groups": 2,
            "sample_size": 40,
            "has_pretest": True,
            "is_normal": True
        }
        res = self.stat_reasoner.consult(profile)
        rec = res["recommendation"]
        self.assertIn("ANCOVA", rec["selected_method"])
        
        # Rejected alternatives must explicitly reject gain-score t-test
        rejected_names = [alt["option"] for alt in res["rejected_alternatives"]]
        self.assertTrue(any("Gain Score" in opt for opt in rejected_names))

    def test_admin_desk_and_decision_journaling(self):
        """Directive 7 & 11: Asserts Admin Desk (124911145) approval gate and decision journaling."""
        bridge = TelegramCopilotBridge()
        proposal_text = "اثربخشی درمان مبتنی بر پذیرش و تعهد بر اضطراب مرگ بیماران قلبی"
        record = bridge.draft_proposal_quote(proposal_text, client_name="تست سیستم")
        qid = record["quote_id"]
        self.assertIn("Q", qid)

        # Approve via Admin Desk ID 124911145
        approval = bridge.approve_quote(qid, adjusted_price=7500000)
        self.assertEqual(approval["status"], "success")
        self.assertEqual(approval["total_price"], 7500000)

        # Log to decision journal
        journal = DecisionJournalEngine()
        did = journal.log_decision(
            decision_type="pricing",
            context=f"Test quotation {qid} release",
            selected_option="Approve 7,500,000 Tomans",
            rationale="Admin Gate clearance test",
            alternatives_considered=[{"option": "7,500,000 Tomans"}],
            human_gate_required=True,
            human_gate_approved=True,
            approved_by="GhaderiSaber (124911145)"
        )
        self.assertTrue(did.startswith("dec_"))

        # Verify decision file on disk
        decision_path = os.path.join(MEMORY_DIR, "decisions", f"{did}.json")
        self.assertTrue(os.path.isfile(decision_path))
        with open(decision_path, "r", encoding="utf-8") as f:
            saved_dec = json.load(f)
        self.assertEqual(saved_dec["approved_by"], "GhaderiSaber (124911145)")
        self.assertTrue(saved_dec["human_gate_approved"])

        # Clean up test decision file
        if os.path.exists(decision_path):
            os.remove(decision_path)

    def test_webapp_standalone_and_rest_endpoints(self):
        """Pillar 5: Asserts standalone WebApp assets exist and serve_webapp diagnostics pass."""
        webapp_dir = os.path.join(REPO_ROOT, "webapp")
        standalone_html = os.path.join(webapp_dir, "standalone.html")
        style_css = os.path.join(webapp_dir, "css", "style.css")
        app_js = os.path.join(webapp_dir, "js", "app.js")
        seed_js = os.path.join(webapp_dir, "data", "seed_data.js")

        for fpath in [standalone_html, style_css, app_js, seed_js]:
            self.assertTrue(os.path.isfile(fpath), f"Missing required asset: {fpath}")
            self.assertGreater(os.path.getsize(fpath), 500, f"Asset {fpath} is unexpectedly small")

        # Run serve_webapp test suite
        res = run_web_test_server()
        self.assertEqual(res, 0)


if __name__ == "__main__":
    unittest.main()
