#!/usr/bin/env python3
"""
Human Scholarly Manuscript Generator & Burstiness Optimizer
Skill #22: ai-academic-tone-polisher implementation
"""

import re
import numpy as np

# ==============================================================================
# SECTION 1: REWRITTEN HUMAN SCHOLARLY TEXT
# ==============================================================================

introduction = [
    # Para 1: Phenomenological Hook & Burden
    "Pain is rarely just physical. For college students, persistent bodily discomfort presents a quiet, daily struggle—disrupting sleep, forcing missed classes, and derailing concentration during critical exams (Treede et al., 2015; McCarthy et al., 2023). While clinical medicine traditionally viewed chronic pain as an ailment of older populations, contemporary campus epidemiological surveys reveal a far more concerning reality. Between 15% and 40% of enrolled university students now endure recurrent musculoskeletal, neuropathic, or visceral discomfort that persists well past the standard three-month diagnostic threshold (Gloria-Kang et al., 2020; Raffaeli et al., 2021). This is not ordinary exam-week muscle tightness. It is enduring physical distress that directly collides with the developmental challenges of emerging adulthood. Left unaddressed, persistent pain during these formative years triggers a compounding cycle of academic absenteeism, heightened depressive symptoms, and regular dependence on over-the-counter analgesics (Alsaggaf & Coyne, 2020; Smale et al., 2023).",

    # Para 2: Personality Vulnerability & Resilience
    "Why do two young adults with comparable bodily discomfort experience vastly different degrees of suffering? Contemporary biopsychosocial frameworks emphasize that subjective pain is never a direct 1-to-1 reflection of peripheral nociceptive input; it is continuously modulated by cognitive appraisals, affective states, and enduring personality traits (Martínez et al., 2020). The Five-Factor Model provides a well-validated lens for examining these individual differences (Costa & McCrae, 1992). Among the Big Five domains, neuroticism stands out as the most consistent psychological vulnerability factor for chronic pain (Grouper et al., 2021). Students with elevated neuroticism exhibit an attentional bias toward somatic signals, frequently interpreting ambiguous bodily sensations through catastrophic lenses—ruminating on their discomfort, magnifying perceived threat, and feeling helpless (Asghari & Nicholas, 2005; Wong et al., 2014). Conversely, conscientiousness, extraversion, and agreeableness appear to serve protective roles. Conscientious students tend to preserve regular sleep hygiene and self-care schedules, extraverts readily mobilize peer support when distress escalates, and agreeable individuals maintain cooperative relationships that buffer autonomic stress responses (Newth & DeLongis, 2004; Krok & Baker, 2014; Rubén et al., 2023). Yet core personality traits represent deeply anchored dispositions that resist brief psychological interventions. Clinical reality thus demands identifying malleable cognitive-affective processes that sit between fixed personality traits and the lived experience of bodily pain.",

    # Para 3: Mechanistic Mediator - Self-Compassion
    "In this context, self-compassion represents a compelling regulatory mechanism. Rather than cultivating defensive self-esteem or positive illusions, self-compassion involves treating oneself with kindness and understanding when encountering personal flaws, suffering, or physical limitation (Neff, 2003a). Neff conceptualizes this stance across three interconnected dimensions: self-kindness versus harsh self-judgment, common humanity versus feelings of isolation, and mindfulness versus over-identification (Neff, 2003b; Barnard & Curry, 2011). In chronic pain populations, this orientation fundamentally reshapes how individuals relate to somatic distress (Costa & Pinto-Gouveia, 2011). Rather than viewing a pain flare-up as a personal failure or an all-consuming disaster, self-compassionate individuals recognize physical discomfort as an unwelcome but shared aspect of the human condition, holding painful sensations in balanced, non-reactive awareness (Davey et al., 2020). Drawing on Gilbert’s (2014) evolutionary model of affect regulation, self-compassion stimulates neurobiological soothing circuits, dampening the sympathetic hyperarousal and chronic threat states that amplify central nociceptive signaling (Carvalho et al., 2018). Clinical investigations corroborate this pathway: higher self-compassion correlates with reduced pain-related disability, lower catastrophizing, and better psychological functioning across varied medical cohorts (Wren et al., 2012; Lanzaro et al., 2024; Mistretta et al., 2023).",

    # Para 4: Empirical Gap & SEM Rationale
    "How does self-compassion intersect with broad personality structure? Empirical work indicates that self-compassion correlates inversely with neuroticism while sharing positive links with extraversion, agreeableness, and conscientiousness (Thurackal et al., 2016; Baker, 2023). When pain intensifies, students burdened by high neuroticism often succumb to self-blame and emotional withdrawal, stripping away their capacity for self-directed kindness (Muris & Otgaar, 2020; Krejčová et al., 2023). In contrast, emotionally stable and conscientious students find it substantially easier to adopt mindful, balanced coping perspectives (Mohtarami Zavardeh et al., 2023; Qadriyah et al., 2020). Despite these plausible linkages, few empirical investigations have tested whether self-compassion formally mediates the pathway between Big Five personality dimensions and chronic pain intensity in young adults. Much of the extant literature relies on simple bivariate correlations or standard linear regression—analytical methods that cannot simultaneously model multidimensional constructs, account for measurement error, or parse indirect structural pathways (Ardalani Farsa et al., 2021; Rezvani & Sajjadian, 2017). Structural equation modeling (SEM) provides the statistical rigor required to determine whether self-compassion functions as an authentic affective bridge connecting latent personality dimensions to subjective pain intensity.",

    # Para 5: Study Aims & Hypotheses
    "To address this gap, we evaluated a structural mediation model within a clinically screened sample of university students experiencing chronic pain. Our investigation was guided by four specific hypotheses: First, Big Five personality traits will significantly predict chronic pain severity, with neuroticism predicting greater pain intensity and adaptive traits predicting lower pain (H1). Second, personality traits will significantly predict self-compassion, with neuroticism predicting lower self-compassion and adaptive traits predicting higher self-compassion (H2). Third, self-compassion will directly and negatively predict chronic pain severity (H3). Finally, self-compassion will partially mediate the structural association between latent personality dimensions and subjective pain severity (H4)."
]

method = {
    "design_and_participants": "We employed a cross-sectional, descriptive correlational design evaluated through Structural Equation Modeling (SEM). The study population comprised undergraduate, master's, and doctoral students enrolled at Kashan University of Medical Sciences (KAUMS, Kashan, Iran) during the 2023–2024 academic year. Recruitment proceeded through digital student channels, departmental announcement boards, and campus health center bulletins. Participants were required to meet four strict eligibility criteria: (a) active enrollment at KAUMS, (b) age 18 years or older, (c) self-reported persistent or recurrent bodily pain enduring for a minimum of three consecutive months prior to assessment (verified via standardized clinical screening), and (d) provision of informed electronic consent. Exclusion criteria encompassed acute pain originating from surgical interventions or major trauma within the preceding three months, active cognitive or psychotic disorders that would impair survey comprehension, or incomplete survey submissions. A total of 304 eligible students satisfied all criteria and completed the study protocol without missing data. Sample size adequacy was verified a priori using G*Power (Version 3.1.9.7): specifying a medium effect size (f² = 0.15), α = .05, statistical power of (1 - β) = .95, and six model predictors indicated a minimum requirement of 172 participants. Our achieved sample of N = 304 also comfortably surpassed established SEM recommendations of 5 to 10 respondents per free model parameter (Kline, 2015; Bentler & Chou, 1987), providing a robust ratio of 11.7 participants per parameter across 26 freely estimated parameters.",

    "measures": "We administered three well-validated psychological instruments:\n\n1. Visual Analogue Scale (VAS): Chronic pain intensity was measured using a standardized 10-cm horizontal Visual Analogue Scale (Price et al., 1983; Carlsson, 1983). The scale is bounded by polar verbal anchors: '0' denoting 'no pain at all' and '10' denoting 'worst imaginable pain.' Students marked the point corresponding to their average pain severity over the preceding four weeks. The VAS represents an international benchmark in pain research, displaying excellent sensitivity to subjective differences and high test-retest reliability (r = .97; Delgado et al., 2018; Freeman et al., 2001).\n\n2. NEO Five-Factor Inventory (NEO-FFI): Personality dimensions were assessed using the 60-item short-form inventory developed by Costa and McCrae (1992). The instrument captures five broad domains with 12 items each: Neuroticism (N), Extraversion (E), Openness to Experience (O), Agreeableness (A), and Conscientiousness (C). Each item is rated along a 5-point Likert scale ranging from 0 ('Strongly disagree') to 4 ('Strongly agree'), yielding domain scores between 0 and 48. The Persian adaptation has demonstrated solid construct validity and psychometric reliability among Iranian university students, with Cronbach’s alpha coefficients ranging from .74 to .86 across dimensions (Roshan et al., 2006; Garousi et al., 2001; Anisi et al., 2012).\n\n3. Self-Compassion Scale - Short Form (SCS-SF): Self-compassionate responding was evaluated via the 12-item SCS-SF (Raes et al., 2011). The scale measures six balanced subscales: Self-Kindness (e.g., 'I try to be understanding and patient towards those aspects of my personality I don't like'), Self-Judgment (e.g., 'I’m disapproving and judgmental about my own flaws and inadequacies'), Common Humanity (e.g., 'I try to see my failings as part of the human condition'), Isolation (e.g., 'When I'm feeling down, I tend to feel like most other people are probably happier than I am'), Mindfulness (e.g., 'When something painful happens I try to take a balanced view of the situation'), and Over-Identification (e.g., 'When I’m feeling down I tend to obsess and fixate on everything that’s wrong'). Items are scored from 1 ('Almost never') to 5 ('Almost always'). Following reverse-scoring of uncompassionate items, a total composite score is calculated, with higher scores reflecting greater self-compassion. The Persian version exhibits strong internal consistency (α = .86) and correlates almost perfectly with the original 26-item long form (r ≥ .97; Shahbazi et al., 2015; Khosravi et al., 2013).",

    "procedure": "The research protocol received formal ethical approval from the Institutional Research Ethics Committee of Kashan University of Medical Sciences (Grant No. 403043) and strictly adhered to the Declaration of Helsinki. Students accessed the questionnaire battery via an encrypted web portal. An introductory landing page outlined the study objectives, emphasized that participation was entirely voluntary, guaranteed full anonymity, and assured students that choosing to withdraw would incur no academic penalty. Survey completion required approximately 20 minutes. All incoming survey data were recorded directly into an encrypted, password-protected server.",

    "statistical_analysis": "Preliminary data screening and descriptive calculations were executed in IBM SPSS Statistics (Version 26.0). We screened for multivariate outliers using Mahalanobis distance (p < .001) and verified univariate normality through skewness and kurtosis coefficients within the accepted [-1.0, +1.0] range (Kline, 2015). We subsequently employed the lavaan structural equation modeling package (Version 0.6-19; Rosseel, 2012) in R (Version 4.3.0) using Maximum Likelihood (ML) estimation. We adopted the classic two-step analytical procedure outlined by Anderson and Gerbing (1988): first validating the measurement model via Confirmatory Factor Analysis (CFA), then testing the structural mediation model. Latent personality was defined by the five NEO-FFI trait scores, latent self-compassion was indicated by the six SCS-SF facet scores, and pain severity was represented by the observed VAS score. Goodness-of-fit was judged against standard empirical cutoffs (Hu & Bentler, 1999; Kline, 2015): non-significant chi-square (p > .05), χ²/df ≤ 2.0, CFI ≥ .95, TLI ≥ .95, RMSEA ≤ .06 (with 90% confidence intervals and non-significant p_close), and SRMR ≤ .08. We tested the significance of the indirect effect using the product-of-coefficients method (a × c), calculating standard errors, z-statistics, and 95% confidence intervals."
}

results_narrative = [
    # Para 1: Demographics
    "Table 1 outlines the demographic profile of the 304 participating students. Women comprised 73.7% of the cohort (n = 224) and men accounted for 26.3% (n = 80), a gender breakdown consistent with Iranian health sciences enrollment. Participant ages spanned 17 to 48 years (M = 23.90, SD = 5.61), with the largest segment (47.0%, n = 143) falling between 21 and 25 years. Regarding academic degree programs, 41.4% (n = 126) were undergraduate students, 24.3% (n = 74) were enrolled in master's programs, and 33.9% (n = 103) were pursuing medical or doctoral degrees (one student did not report degree level). Furthermore, 38.2% of the participants (n = 116) reported taking analgesic medications regularly for pain management, while 61.8% (n = 188) relied solely on non-pharmacological coping strategies.",

    # Para 2: Descriptives & Normality
    "Table 2 reports descriptive parameters and normality indices for all study variables. The mean chronic pain severity score was 5.04 (SD = 1.76; observed range 0 to 10), indicating moderate baseline pain. The mean composite self-compassion score was 39.30 (SD = 5.65; range 22 to 55). Across Big Five personality traits, mean scores were 25.14 (SD = 4.99) for neuroticism, 19.88 (SD = 3.35) for extraversion, 22.89 (SD = 3.98) for openness, 20.00 (SD = 3.12) for agreeableness, and 19.10 (SD = 3.32) for conscientiousness. Skewness indices ranged from -0.32 to 0.23, and kurtosis values ranged from -0.19 to 1.09. All values remained well within the standard [-1.0, +1.0] threshold, confirming acceptable univariate normality across variables.",

    # Para 3: Pearson Correlations
    "Bivariate Pearson correlations appear in Table 3. In line with theoretical expectations, chronic pain severity showed a moderate, statistically significant inverse correlation with self-compassion (r = -.513, p < .001). Students reporting greater self-compassion experienced noticeably milder chronic pain. Regarding personality dimensions, pain severity was positively associated with neuroticism (r = .398, p < .001), while correlating negatively with extraversion (r = -.364, p < .001), openness (r = -.381, p < .001), agreeableness (r = -.341, p < .001), and conscientiousness (r = -.430, p < .001). In contrast, self-compassion correlated negatively with neuroticism (r = -.320, p < .001), while displaying positive correlations with extraversion (r = .304, p < .001), openness (r = .381, p < .001), agreeableness (r = .310, p < .001), and conscientiousness (r = .365, p < .001).",

    # Para 4: Measurement Model
    "Prior to evaluating structural pathways, we tested the measurement model to confirm that observed indicators adequately reflected their intended latent constructs. Table 4 presents the standardized factor loadings (λ), all of which achieved statistical significance at p < .001. For latent personality, neuroticism loaded positively (λ = .599, z = fixed reference), whereas extraversion (λ = -.663, z = -8.744), openness (λ = -.701, z = -9.062), agreeableness (λ = -.668, z = -8.786), and conscientiousness (λ = -.674, z = -8.837) loaded negatively. This loading configuration defines a cohesive latent continuum where higher scores capture elevated neurotic vulnerability versus emotional resilience. For latent self-compassion, all six subscales exhibited substantial, statistically significant loadings: over-identification (λ = .668, z = fixed reference), self-kindness (λ = .739, z = 11.028), mindfulness (λ = .703, z = 10.592), isolation (λ = .699, z = 10.537), common humanity (λ = .719, z = 10.789), and self-judgment (λ = .721, z = 10.818). These results confirmed adequate convergent validity for both latent constructs.",

    # Para 5: Structural Model Fit
    "We next evaluated the structural mediation model via maximum likelihood estimation in lavaan. The hypothesized model demonstrated an exceptional fit to the empirical data: χ²(52, N = 304) = 57.762, p = .271; χ²/df = 1.111; baseline χ²(66) = 1345.732, p < .001; CFI = .995; TLI = .994; RMSEA = .019 (90% CI [.000, .042], p_close = .990); and SRMR = .032. The non-significant chi-square statistic, alongside the favorable RMSEA and SRMR values, indicates that the structural model successfully reproduced the sample covariance matrix.",

    # Para 6: Structural Pathways & Mediation
    "Table 5 details the unstandardized and standardized path estimates, standard errors, z-values, and 95% confidence intervals; Figure 1 depicts the model graphically. Personality traits exerted a significant negative effect on self-compassion (path a: B = -0.151, SE = 0.023, z = -6.449, p < .001, β = -.544, 95% CI [-0.197, -0.105]). Students with higher neuroticism and lower adaptive traits reported substantially lower self-compassion. Self-compassion, in turn, exerted a direct negative effect on pain severity (path c: B = -0.732, SE = 0.143, z = -5.117, p < .001, β = -.344, 95% CI [-1.013, -0.452]). The direct path from personality to pain severity also remained significant (path e: B = 0.228, SE = 0.043, z = 5.312, p < .001, β = .387, 95% CI [0.144, 0.312]). Crucially, the indirect effect of personality on pain severity through self-compassion was statistically significant (path a × c: B = 0.110, SE = 0.024, z = 4.512, p < .001, β_indirect = .187, 95% CI [0.062, 0.158]). The total effect was likewise significant (B = 0.338, SE = 0.046, z = 7.348, p < .001, β_total = .574, 95% CI [0.248, 0.428]). Because both direct and indirect pathways reached significance, the findings establish partial mediation, with self-compassion accounting for roughly 32.6% of the total association between personality traits and chronic pain severity."
]

discussion = [
    # Para 1: Overview
    "Chronic bodily pain among university students is frequently dismissed as simple exam strain or poor study posture, yet its emotional and academic toll can be debilitating. We evaluated whether self-compassion serves as an affective buffer mediating the pathway between Big Five personality traits and chronic pain severity. The empirical data provided unambiguous support for this framework. Our structural equation model reproduced the observed sample covariances with exceptional precision, demonstrating that personality traits shape chronic pain not only directly, but also indirectly through self-compassion. In essence, self-compassion functions as an internal psychological shock absorber. It helps explain why students burdened by neurotic vulnerability suffer more severely from physical symptoms, whereas emotionally resilient students experience meaningful relief.",

    # Para 2: Personality Direct Links (H1)
    "In support of our initial hypothesis (H1), personality dimensions demonstrated robust bivariate and structural links to pain severity. Neuroticism was the sole Big Five trait positively linked to pain intensity (r = .398), corroborating extensive clinical literature that identifies affective instability as a primary psychological risk in chronic pain (Grouper et al., 2021; Wong et al., 2014; Ibrahim et al., 2020). Students high in neuroticism tend to maintain an attentional stance of somatic hypervigilance. When discomfort strikes, they often catastrophize—magnifying perceived threat and feeling powerless—a response known to heighten nociceptive signaling within the central nervous system (Asghari & Nicholas, 2005; Martínez et al., 2020). Conversely, conscientiousness, extraversion, and agreeableness showed protective associations. Conscientious students tend to manage health regimens and sleep habits more reliably, extraverts mobilize peer support to manage emotional distress, and agreeable individuals sustain supportive social ties that lower neuroendocrine stress responses (Newth & DeLongis, 2004; Krok & Baker, 2014; Rubén et al., 2023).",

    # Para 3: Self-Compassion Links (H2 & H3)
    "Our second and third hypotheses (H2 and H3) were likewise substantiated. Latent personality strongly predicted self-compassion (β = -.544), and self-compassion in turn exerted a direct, inhibitory effect on chronic pain severity (β = -.344). Students who practiced greater self-compassion reported significantly less intense pain (r = -.513). What physiological and affective processes explain this protective influence? Gilbert’s (2014) evolutionary model of affect regulation provides a compelling explanation. When physical pain flares up, the human threat-defense system naturally activates, triggering autonomic arousal, muscle guarding, and neuroendocrine stress. Self-compassion interrupts this cascade. By meeting discomfort with self-kindness instead of frustration, viewing suffering as part of common humanity rather than isolating defectiveness, and holding bodily sensations in balanced mindfulness, students de-escalate threat appraisals and engage the neurobiological soothing system (Carvalho et al., 2018). This transition dampens sympathetic arousal and calms central pain amplification (Wren et al., 2012; Lanzaro et al., 2024; Mistretta et al., 2023).",

    # Para 4: Mediation Mechanism (H4)
    "The central finding of our investigation was confirming that self-compassion partially mediates the pathway from personality traits to chronic pain severity (indirect β = .187, p < .001), validating our fourth hypothesis (H4). A personality profile marked by high neuroticism and low conscientiousness appears to compromise a student's capacity for self-compassion. During pain flare-ups, these vulnerable students often collapse into self-blame and emotional isolation, compounding their physical suffering. Resilient personality profiles, by contrast, nurture self-compassion, providing an affective buffer that tempers the subjective burden of physical symptoms. Because mediation was partial, personality traits also retained a direct path to pain severity (β = .387). These direct linkages likely reflect neurobiological pain thresholds, autonomic reactivity, and genetic differences in nociceptive processing (Grouper et al., 2021).",

    # Para 5: Clinical & Campus Implications
    "These findings offer clear, practical direction for campus counseling centers and student health services. Modifying core personality traits like neuroticism through short-term clinical therapy is notoriously difficult. Self-compassion, by contrast, is a trainable behavioral and cognitive skill that responds rapidly to structured training (Neff & Germer, 2013). University students with chronic pain—especially those struggling with perfectionism, neurotic vulnerability, or academic pressure—would benefit substantially from structured compassion training. Group programs based on Mindful Self-Compassion (MSC; Neff & Germer, 2013) or Compassion-Focused Therapy (CFT; Gilbert, 2014) could provide accessible, non-pharmacological tools to help students break cycles of self-criticism, diminish pain catastrophizing, and navigate symptom flare-ups with greater equanimity.",

    # Para 6: Strengths, Limitations & Future Directions
    "This investigation has several notable strengths, including a verified clinical sample of 304 university students with persistent pain, the use of structural equation modeling to account for measurement error, and simultaneous examination of all Big Five traits alongside the six self-compassion facets. At the same time, certain methodological limitations should be considered. First, because our design was cross-sectional, we cannot make definitive causal inferences. Longitudinal investigations and randomized controlled trials are needed to confirm whether boosting self-compassion directly lowers chronic pain over time. Second, we relied on self-report questionnaires, which carry inherent risks of recall and social desirability biases, although guaranteed anonymity helped mitigate this concern. Third, our sample was recruited via convenience sampling from a single medical sciences university in Iran and consisted predominantly of female students (73.7%). While this distribution matches the gender makeup of Iranian healthcare faculties, future studies should examine whether these pathways generalize to non-medical students and other cultural environments. Finally, our study captured general pain severity with the VAS; exploring specific etiologies—such as tension headaches, lower back pain, or dysmenorrhea—could clarify whether self-compassion buffers certain pain types more effectively than others.",

    # Para 7: Conclusion
    "In conclusion, our study demonstrates that self-compassion serves as an essential affective mediator linking Big Five personality traits to chronic pain severity in university students. Personality influences subjective pain not only directly, but also by shaping a student's capacity for self-directed kindness and mindful acceptance. Cultivating self-compassion represents a practical, scalable clinical strategy to reduce chronic pain suffering and support student wellbeing in higher education."
]

declarations = {
    "ethics_approval": "This study was conducted in strict accordance with the Declaration of Helsinki and received formal ethical approval from the Institutional Research Ethics Committee of Kashan University of Medical Sciences (Grant No. 403043).",
    "consent_to_participate": "All participants provided electronic informed consent before completing the survey.",
    "data_availability": "The datasets generated and analyzed during the current study are available from the corresponding author upon reasonable academic request.",
    "conflict_of_interest": "The authors declare no competing financial or personal interests.",
    "funding": "This research received partial financial support from Kashan University of Medical Sciences (Grant No. 403043; KAUMS Portal: http://pajouhan.kaums.ac.ir/generateSystemReport.action?type=5&id=403043).",
    "authors_contributions": "Z.J. conceived the study idea, oversaw on-campus participant recruitment, and prepared the preliminary manuscript draft. H.A. supervised study design and methodology, performed structural equation modeling in R, directed project administration, and critically revised the article. A.O. provided clinical and psychiatric supervision, contributed to theoretical conceptualization, and reviewed and approved the final manuscript for publication."
}

def analyze_burstiness_and_markers(texts, name="Section"):
    full_text = " ".join(texts)
    sents = [s.strip() for s in re.split(r'(?<=[.!?])\s+', full_text) if len(s.strip()) > 5]
    lens = [len(s.split()) for s in sents]
    mean_l = np.mean(lens) if lens else 0
    std_l = np.std(lens) if lens else 0
    cv_l = std_l / mean_l if mean_l > 0 else 0
    
    ai_cliches = [
        'plays a crucial role', 'crucial role', 'pivotal role', 'vital role', 'delve',
        'sheds light', 'paves the way', 'multifaceted', 'intricate', 'testament',
        'fostering', 'seamlessly', 'garnered', 'underscores', 'compelling evidence',
        'it is worth noting', 'it is important to note', 'notably', 'furthermore',
        'moreover', 'in this regard', 'subsequently', 'indispensable'
    ]
    found = []
    for m in ai_cliches:
        cnt = len(re.findall(r'\b' + re.escape(m) + r'\b', full_text, re.I))
        if cnt > 0:
            found.append(f"{m} ({cnt})")
            
    print(f"[{name}] Sentences: {len(sents)} | Mean Words: {mean_l:.1f} | Std: {std_l:.1f} | CV: {cv_l:.2f} | Cliches: {len(found)}")
    if found:
        print(f"   Found: {found}")
    return cv_l, len(found)

if __name__ == "__main__":
    print("=== Testing Refined Human Scholarly Manuscript ===")
    analyze_burstiness_and_markers(introduction, "Introduction")
    analyze_burstiness_and_markers([method["design_and_participants"], method["measures"], method["procedure"], method["statistical_analysis"]], "Method")
    analyze_burstiness_and_markers(results_narrative, "Results")
    analyze_burstiness_and_markers(discussion, "Discussion")
